name: flutter_bluetooth_serial
description: A basic Flutter Bluetooth Serial
version: 0.0.5
author: Eduardo Folly <edufolly@gmail.com>
homepage: https://github.com/edufolly/flutter_bluetooth_serial

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.github.edufolly.flutterbluetoothserial
    pluginClass: FlutterBluetoothSerialPlugin

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/ppj/signature.bmp
  fonts:
    - family: barcode39
      fonts:
        - asset: assets/fonts/Barcode39.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: arial
      fonts:
        - asset: assets/fonts/arial/arial.ttf

environment:
  sdk: ">=2.0.0-a <3.0.0"
